CREATE TABLE CLIENTS 
   (CODECLIENT VARCHAR2(6) PRIMARY key, 
	SOCIÉTÉ VARCHAR2(100) NOT NULL, 
	CONTACT VARCHAR2(100) not null, 
	FONCTION VARCHAR2(100) not null,
	ADRESSE VARCHAR2(100), 
	VILLE VARCHAR2(100), 
	NAISSANCE DATE,
    RÉGION VARCHAR2(100),
	CODE_POSTAL VARCHAR2(10), 
	PAYS VARCHAR2(100),
    TÉLÉPHONE VARCHAR2(100),
    FAX VARCHAR2(100)
   );


Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('BERGS','Berglunds snabbköp','Christina Berglund','Acheteur','Berguvsvägen  8','Luleå',to_date('25/08/72','DD/MM/RR'),null,'S-958 22','Suède','0921-12 34 65','0921-12 34 67');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('BLAUS','Blauer See Delikatessen','Hanna Moos','Représentant(e)','Forsterstr. 57','Mannheim',to_date('16/02/73','DD/MM/RR'),null,'68306','Allemagne','0621-08460','0621-08924');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('BLONP','Blondel père et fils','Frédérique Citeaux','Directeur du marketing','24, place Kléber','Strasbourg',to_date('07/04/73','DD/MM/RR'),null,'67000','France','03.88.60.15.31','03.88.60.15.32');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('BOLID','Bólido Comidas preparadas','Martín Sommer','Propriétaire','C/ Araquil, 67','Madrid',to_date('19/04/73','DD/MM/RR'),null,'28023','Espagne','(91) 555 22 82','(91) 555 91 99');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('BONAP','Bon app''','Laurence Lebihan','Propriétaire','12, rue des Bouchers','Marseille',to_date('12/09/73','DD/MM/RR'),null,'13008','France','04.91.24.45.40','04.91.24.45.41');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('BOTTM','Bottom-Dollar Markets','Elizabeth Lincoln','Chef comptable','23 Tsawassen Blvd.','Tsawassen',to_date('12/11/73','DD/MM/RR'),'BC','T2F 8M4','Canada','(604) 555-4729','(604) 555-3745');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('BSBEV','B''s Beverages','Victoria Ashworth','Représentant(e)','Fauntleroy Circus','London',to_date('19/10/74','DD/MM/RR'),null,'EC2 5NT','Royaume-Uni','(71) 555-1212',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('CACTU','Cactus Comidas para llevar','Patricio Simpson','Assistant(e) des ventes','Cerrito 333','Buenos Aires',to_date('09/10/75','DD/MM/RR'),null,'1010','Argentine','(1) 135-5555','(1) 135-4892');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('CENTC','Centro comercial Moctezuma','Francisco Chang','Directeur du marketing','Sierras de Granada 9993','México D.F.',to_date('24/02/76','DD/MM/RR'),null,'05022','Mexique','(5) 555-3392','(5) 555-7293');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('CHOPS','Chop-suey Chinese','Yang Wang','Propriétaire','Hauptstr. 29','Bern',to_date('01/10/76','DD/MM/RR'),null,'3012','Suisse','0452-076545',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('COMMI','Comércio Mineiro','Pedro Afonso','Assistant(e) des ventes','Av. dos Lusíadas, 23','São Paulo',to_date('13/11/76','DD/MM/RR'),'SP','05432-043','Brésil','(11) 555-7647',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('CONSH','Consolidated Holdings','Elizabeth Brown','Représentant(e)','Berkeley Gardens
12  Brewery ','London',to_date('24/01/77','DD/MM/RR'),null,'WX1 6LT','Royaume-Uni','(71) 555-2282','(71) 555-9199');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('DRACD','Drachenblut Delikatessen','Sven Ottlieb','Acheteur','Walserweg 21','Aachen',to_date('08/07/77','DD/MM/RR'),null,'52066','Allemagne','0241-039123','0241-059428');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('DUMON','Du monde entier','Janine Labrune','Propriétaire','67, rue des Cinquante Otages','Nantes',to_date('15/07/77','DD/MM/RR'),null,'44000','France','02.40.67.88.88','02.40.67.89.89');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('EASTC','Eastern Connection','Ann Devon','Assistant(e) des ventes','35 King George','London',to_date('03/12/77','DD/MM/RR'),null,'WX3 6FW','Royaume-Uni','(71) 555-0297','(71) 555-3373');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('ERNSH','Ernst Handel','Roland Mendel','Chef des ventes','Kirchgasse 6','Graz',to_date('15/03/78','DD/MM/RR'),null,'8010','Autriche','7675-3425','7675-3426');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('FAMIA','Familia Arquibaldo','Aria Cruz','Assistant(e) marketing','Rua Orós, 92','São Paulo',to_date('01/11/78','DD/MM/RR'),'SP','05442-030','Brésil','(11) 555-9857',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('FISSA','FISSA Fabrica Inter. Salchichas S.A.','Diego Roel','Chef comptable','C/ Moralzarzal, 86','Madrid',to_date('19/05/79','DD/MM/RR'),null,'28034','Espagne','(91) 555 94 44','(91) 555 55 93');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('FOLIG','Folies gourmandes','Martine Rancé','Représentant(e)','184, chaussée de Tournai','Lille',to_date('13/03/80','DD/MM/RR'),null,'59000','France','03.20.16.10.16','03.20.16.10.17');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('FOLKO','Folk och fä HB','Maria Larsson','Propriétaire','Åkergatan 24','Bräcke',to_date('27/05/80','DD/MM/RR'),null,'S-844 67','Suède','0695-34 67 21',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('FRANK','Frankenversand','Peter Franken','Directeur du marketing','Berliner Platz 43','München',to_date('09/03/81','DD/MM/RR'),null,'80805','Allemagne','089-0877310','089-0877451');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('FRANR','France restauration','Carine Schmitt','Directeur du marketing','54, rue Royale','Nantes',to_date('21/12/81','DD/MM/RR'),null,'44000','France','02.40.32.21.21','02.40.32.21.20');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('FRANS','Franchi S.p.A.','Paolo Accorti','Représentant(e)','Via Monte Bianco 34','Torino',to_date('24/01/82','DD/MM/RR'),null,'10100','Italie','011-4988260','011-4988261');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('FURIB','Furia Bacalhau e Frutos do Mar','Lino Rodriguez ','Chef des ventes','Jardim das rosas n. 32','Lisboa',to_date('02/06/82','DD/MM/RR'),null,'1675','Portugal','(1) 354-2534','(1) 354-2535');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('GALED','Galería del gastrónomo','Eduardo Saavedra','Directeur du marketing','Rambla de Cataluña, 23','Barcelona',to_date('18/02/83','DD/MM/RR'),null,'08022','Espagne','(93) 203 4560','(93) 203 4561');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('GODOS','Godos Cocina Típica','José Pedro Freyre','Chef des ventes','C/ Romero, 33','Sevilla',to_date('23/01/84','DD/MM/RR'),null,'41101','Espagne','(95) 555 82 82',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('GOURL','Gourmet Lanchonetes','André Fonseca','Assistant(e) des ventes','Av. Brasil, 442','Campinas',to_date('31/08/84','DD/MM/RR'),'SP','04876-786','Brésil','(11) 555-9482',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('GREAL','Great Lakes Food Market','Howard Snyder','Directeur du marketing','2732 Baker Blvd.','Eugene',to_date('05/11/84','DD/MM/RR'),'OR','97403','États-Unis','(503) 555-7555',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('GROSR','GROSELLA-Restaurante','Manuel Pereira','Propriétaire','5ª Ave. Los Palos Grandes','Caracas',to_date('09/04/85','DD/MM/RR'),'DF','1081','Venezuela','(2) 283-2951','(2) 283-3397');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('HANAR','Hanari Carnes','Mario Pontes','Chef comptable','Rua do Paço, 67','Rio de Janeiro',to_date('10/08/85','DD/MM/RR'),'RJ','05454-876','Brésil','(21) 555-0091','(21) 555-8765');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('HILAA','HILARIÓN-Abastos','Carlos Hernández','Représentant(e)','Carrera 22 con Ave. Carlos Soublette #8-35','San Cristóbal',to_date('07/06/86','DD/MM/RR'),'Táchira','5022','Venezuela','(5) 555-1340','(5) 555-1948');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('HUNGC','Hungry Coyote Import Store','Yoshi Latimer','Représentant(e)','City Center Plaza
516 Main St.','Elgin',to_date('26/04/87','DD/MM/RR'),'OR','97827','États-Unis','(503) 555-6874','(503) 555-2376');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('HUNGO','Hungry Owl All-Night Grocers','Patricia McKenna','Assistant(e) des ventes','8 Johnstown Road','Cork',to_date('19/08/87','DD/MM/RR'),'Co. Cork',null,'Irlande','2967 542','2967 3333');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('ISLAT','Island Trading','Helen Bennett','Directeur du marketing','Garden House
Crowther Way','Cowes',to_date('05/07/88','DD/MM/RR'),'Isle of Wight','PO31 7PJ','Royaume-Uni','(198) 555-8888',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('KOENE','Königlich Essen','Philip Cramer','Assistant(e) des ventes','Maubelstr. 90','Brandenburg',to_date('08/07/88','DD/MM/RR'),null,'14776','Allemagne','0555-09876',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('LACOR','La corne d''abondance','Daniel Tonini','Représentant(e)','67, avenue de l''Europe','Versailles',to_date('15/02/89','DD/MM/RR'),null,'78000','France','01.30.59.84.10','01.30.59.85.11');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('LAMAI','La maison d''Asie','Annette Roulet','Chef des ventes','1 rue Alsace-Lorraine','Toulouse',to_date('27/08/89','DD/MM/RR'),null,'31000','France','05.61.77.61.10','05.61.77.61.11');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('LAUGB','Laughing Bacchus Wine Cellars','Yoshi Tannamuri','Assistant(e) marketing','1900 Oak St.','Vancouver',to_date('07/04/90','DD/MM/RR'),'BC','V3F 2K1','Canada','(604) 555-3392','(604) 555-7293');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('LAZYK','Lazy K Kountry Store','John Steel','Directeur du marketing','12 Orchestra Terrace','Walla Walla',to_date('18/10/90','DD/MM/RR'),'WA','99362','États-Unis','(509) 555-7969','(509) 555-6221');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('LEHMS','Lehmanns Marktstand','Renate Messner','Représentant(e)','Magazinweg 7','Frankfurt a.M. ',to_date('18/01/91','DD/MM/RR'),null,'60528','Allemagne','069-0245984','069-0245874');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('LETSS','Let''s Stop N Shop','Jaime Yorres','Propriétaire','87 Polk St.
Suite 5','San Francisco',to_date('10/04/91','DD/MM/RR'),'CA','94117','États-Unis','(415) 555-5938',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('LILAS','LILA-Supermercado','Carlos González','Chef comptable','Carrera 52 con Ave. Bolívar #65-98 Llano Largo','Barquisimeto',to_date('22/05/91','DD/MM/RR'),'Lara','3508','Venezuela','(9) 331-6954','(9) 331-7256');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('LINOD','LINO-Delicateses','Felipe Izquierdo','Propriétaire','Ave. 5 de Mayo Porlamar','I. de Margarita',to_date('12/08/91','DD/MM/RR'),'Nueva Esparta','4980','Venezuela','(8) 34-56-12','(8) 34-93-93');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('LONEP','Lonesome Pine Restaurant','Fran Wilson','Chef des ventes','89 Chiaroscuro Rd.','Portland',to_date('09/06/92','DD/MM/RR'),'OR','97219','États-Unis','(503) 555-9573','(503) 555-9646');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('MAGAA','Magazzini Alimentari Riuniti','Giovanni Rovelli','Directeur du marketing','Via Ludovico il Moro 22','Bergamo',to_date('23/01/93','DD/MM/RR'),null,'24100','Italie','035-640230','035-640231');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('MAISD','Maison Dewey','Catherine Dewey','Assistant(e) des ventes','Rue Joseph-Bens 532','Bruxelles',to_date('12/01/94','DD/MM/RR'),null,'B-1180','Belgique','(02) 201 24 67','(02) 201 24 68');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('MEREP','Mère Paillarde','Jean Fresnière','Assistant(e) marketing','43 rue St. Laurent','Montréal',to_date('26/04/94','DD/MM/RR'),'Québec','H1J 1C3','Canada','(514) 555-8054','(514) 555-8055');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('MORGK','Morgenstern Gesundkost','Alexander Feuer','Assistant(e) marketing','Heerstr. 22','Leipzig',to_date('06/09/71','DD/MM/RR'),null,'04179','Allemagne','0342-023176',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('NORTS','North/South','Simon Crowther','Assistant(e) des ventes','South House
300 Queensbridge','London',to_date('21/12/71','DD/MM/RR'),null,'SW7 1RZ','Royaume-Uni','(71) 555-7733','(71) 555-2530');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('OCEAN','Océano Atlántico Ltda.','Yvonne Moncada','Assistant(e) des ventes','Ing. Gustavo Moncada 8585
Piso 20-A','Buenos Aires',to_date('07/01/72','DD/MM/RR'),null,'1010','Argentine','(1) 135-5333','(1) 135-5535');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('OLDWO','Old World Delicatessen','Rene Phillips','Représentant(e)','2743 Bering St.','Anchorage',to_date('05/11/72','DD/MM/RR'),'AK','99508','États-Unis','(907) 555-7584','(907) 555-2880');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('OTTIK','Ottilies Käseladen','Henriette Pfalzheim','Propriétaire','Mehrheimerstr. 369','Köln',to_date('10/04/73','DD/MM/RR'),null,'50739','Allemagne','0221-0644327','0221-0765721');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('PARIS','Paris spécialités','Marie Bertrand','Propriétaire','265, boulevard Charonne','Paris',to_date('29/07/73','DD/MM/RR'),null,'75012','France','01.42.34.22.66','01.42.34.22.77');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('PERIC','Pericles Comidas clásicas','Guillermo Fernández','Représentant(e)','Calle Dr. Jorge Cash 321','México D.F.',to_date('13/05/73','DD/MM/RR'),null,'05033','Mexique','(5) 552-3745','(5) 545-3745');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('PICCO','Piccolo und mehr','Georg Pipps','Chef des ventes','Geislweg 14','Salzburg',to_date('02/08/73','DD/MM/RR'),null,'5020','Autriche','6562-9722','6562-9723');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('PRINI','Princesa Isabel Vinhos','Isabel de Castro','Représentant(e)','Estrada da saúde n. 58','Lisboa',to_date('01/07/74','DD/MM/RR'),null,'1756','Portugal','(1) 356-5634',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('QUEDE','Que Delícia','Bernardo Batista','Chef comptable','Rua da Panificadora, 12','Rio de Janeiro',to_date('18/01/74','DD/MM/RR'),'RJ','02389-673','Brésil','(21) 555-4252','(21) 555-4545');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('QUEEN','Queen Cozinha','Lúcia Carvalho','Assistant(e) marketing','Alameda dos Canàrios, 891','São Paulo',to_date('07/08/75','DD/MM/RR'),'SP','05487-020','Brésil','(11) 555-1189',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('QUICK','QUICK-Stop','Horst Kloss','Chef comptable','Taucherstraße 10','Cunewalde',to_date('20/01/76','DD/MM/RR'),null,'01307','Allemagne','0372-035188',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('RANCH','Rancho grande','Sergio Gutiérrez','Représentant(e)','Av. del Libertador 900','Buenos Aires',to_date('07/06/76','DD/MM/RR'),null,'1010','Argentine','(1) 123-5555','(1) 123-5556');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('RATTC','Rattlesnake Canyon Grocery','Paula Wilson','Représentant(e)','2817 Milton Dr.','Albuquerque',to_date('21/09/77','DD/MM/RR'),'NM','87110','États-Unis','(505) 555-5939','(505) 555-3620');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('REGGC','Reggiani Caseifici','Maurizio Moroni','Assistant(e) des ventes','Strada Provinciale 124','Reggio Emilia',to_date('09/09/77','DD/MM/RR'),null,'42100','Italie','0522-556721','0522-556722');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('RICAR','Ricardo Adocicados','Janete Limeira','Représentant(e)','Av. Copacabana, 267','Rio de Janeiro',to_date('14/01/78','DD/MM/RR'),'RJ','02389-890','Brésil','(21) 555-3412',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('RICSU','Richter Supermarkt','Michael Holz','Chef des ventes','Grenzacherweg 237','Genève',to_date('12/08/77','DD/MM/RR'),null,'1203','Suisse','0897-034214',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('ROMEY','Romero y tomillo','Alejandra Camino','Chef comptable','Gran Vía, 1','Madrid',to_date('02/04/78','DD/MM/RR'),null,'28001','Espagne','(91) 745 6200','(91) 745 6210');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('SANTG','Santé Gourmet','Jonas Bergulfsen','Propriétaire','Erling Skakkes gate 78','Stavern',to_date('14/09/78','DD/MM/RR'),null,'4110','Norvège','07-98 92 35','07-98 92 47');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('SAVEA','Save-a-lot Markets','Jose Pavarotti','Représentant(e)','187 Suffolk Ln.','Boise',to_date('27/09/78','DD/MM/RR'),'ID','83720','États-Unis','(208) 555-8097',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('SEVES','Seven Seas Imports','Hari Kumar','Chef des ventes','90 Wadhurst Rd.','London',to_date('26/09/79','DD/MM/RR'),null,'OX15 4NB','Royaume-Uni','(71) 555-1717','(71) 555-5646');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('SIMOB','Simons bistro','Jytte Petersen','Propriétaire','Vinbæltet 34','København',to_date('01/02/80','DD/MM/RR'),null,'1734','Danemark','31 12 34 56','31 13 35 57');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('SPECD','Spécialités du monde','Dominique Perrier','Directeur du marketing','25, rue Lauriston','Paris',to_date('31/05/80','DD/MM/RR'),null,'75016','France','01.47.55.60.10','01.47.55.60.20');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('SPLIR','Split Rail Beer','Art Braunschweiger','Chef des ventes','P.O. Box 555','Lander',to_date('22/04/81','DD/MM/RR'),'WY','82520','États-Unis','(307) 555-4680','(307) 555-6525');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('SUPRD','Suprêmes délices','Pascale Cartrain','Chef comptable','Boulevard Tirou, 255','Charleroi',to_date('16/06/81','DD/MM/RR'),null,'B-6000','Belgique','(071) 23 67 22 20','(071) 23 67 22 21');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('THEBI','The Big Cheese','Liz Nixon','Directeur du marketing','89 Jefferson Way
Suite 2','Portland',to_date('25/02/82','DD/MM/RR'),'OR','97201','États-Unis','(503) 555-3612',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('THECR','The Cracker Box','Liu Wong','Assistant(e) marketing','55 Grizzly Peak Rd.','Butte',to_date('12/12/82','DD/MM/RR'),'MT','59801','États-Unis','(406) 555-5834','(406) 555-8083');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('TOMSP','Toms Spezialitäten','Karin Josephs','Directeur du marketing','Luisenstr. 48','Münster',to_date('02/03/83','DD/MM/RR'),null,'44087','Allemagne','0251-031259','0251-035695');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('TORTU','Tortuga Restaurante','Miguel Angel Paolino','Propriétaire','Avda. Azteca 123','México D.F.',to_date('06/03/83','DD/MM/RR'),null,'05033','Mexique','(5) 555-2933',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('TRADH','Tradição Hipermercados','Anabela Domingues','Représentant(e)','Av. Inês de Castro, 414','São Paulo',to_date('25/07/84','DD/MM/RR'),'SP','05634-030','Brésil','(11) 555-2167','(11) 555-2168');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('TRAIH','Trail''s Head Gourmet Provisioners','Helvetius Nagy','Assistant(e) des ventes','722 DaVinci Blvd.','Kirkland',to_date('03/11/84','DD/MM/RR'),'WA','98034','États-Unis','(206) 555-8257','(206) 555-2174');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('VAFFE','Vaffeljernet','Palle Ibsen','Chef des ventes','Smagsløget 45','Århus',to_date('21/11/84','DD/MM/RR'),null,'8200','Danemark','86 21 32 43','86 22 33 44');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('VICTE','Victuailles en stock','Mary Saveley','Assistant(e) des ventes','2, rue du Commerce','Lyon',to_date('27/02/86','DD/MM/RR'),null,'69004','France','04.78.32.54.86','04.78.32.54.87');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('VINET','Vins et alcools Chevalier','Paul Henriot','Chef comptable','59 rue de l''Abbaye','Reims',to_date('11/06/86','DD/MM/RR'),null,'51100','France','03.26.47.15.10','03.26.47.15.11');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('WANDK','Die Wandernde Kuh','Rita Müller','Représentant(e)','Adenauerallee 900','Stuttgart',to_date('04/02/87','DD/MM/RR'),null,'70563','Allemagne','0711-020361','0711-035428');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('WARTH','Wartian Herkku','Pirkko Koskitalo','Chef comptable','Torikatu 38','Oulu',to_date('29/04/87','DD/MM/RR'),null,'90110','Finlande','981-443655','981-443655');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('WELLI','Wellington Importadora','Paula Parente','Chef des ventes','Rua do Mercado, 12','Resende',to_date('22/09/87','DD/MM/RR'),'SP','08737-363','Brésil','(14) 555-8122',null);
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('WHITC','White Clover Markets','Karl Jablonski','Propriétaire','305 - 14th Ave. S.
Suite 3B','Seattle',to_date('23/08/88','DD/MM/RR'),'WA','98128','États-Unis','(206) 555-4112','(206) 555-4115');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('WILMK','Wilman Kala','Matti Karttunen','Assistant du marketing','Keskuskatu 45','Helsinki',to_date('27/10/88','DD/MM/RR'),null,'21240','Finlande','90-224 8858','90-224 8858');
Insert into CLIENTS (CODECLIENT,SOCIÉTÉ,CONTACT,FONCTION,ADRESSE,VILLE,NAISSANCE,RÉGION,CODE_POSTAL,PAYS,TÉLÉPHONE,FAX) values ('WOLZA','Wolski  Zajazd','Zbyszek Piestrzeniewicz','Propriétaire','ul. Filtrowa 68','Warszawa',to_date('22/08/89','DD/MM/RR'),null,'01-012','Pologne','(26) 642-7012','(26) 642-7012');