 CREATE TABLE "FOURNISSEURS" 
   (	"NFOURNISSEUR" NUMBER(10,0) PRIMARY KEY, 
	"SOCIÉTÉFOUR" VARCHAR2(40 CHAR), 
	"CONTACTFOUR" VARCHAR2(30 CHAR), 
	"FONCTIONFOUR" VARCHAR2(40 CHAR), 
	"ADRESSEFOUR" VARCHAR2(60 CHAR), 
	"VILLEFOUR" VARCHAR2(20 CHAR), 
	"RÉGIONFOUR" VARCHAR2(15 CHAR), 
	"CODEPOSTAL" VARCHAR2(10 CHAR), 
	"PAYSFOUR" VARCHAR2(15 CHAR), 
	"TÉLFOUR" VARCHAR2(24 CHAR), 
	"FAXFOUR" VARCHAR2(24 CHAR), 
	"PAGEACCUEIL" VARCHAR2(50)
   ); 

Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('1','Exotic Liquids','Charlotte Cooper','Assistant export','49 Gilbert St.','London',null,'EC1 4SD','Royaume-Uni','(171) 555-2222',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('2','Nouvelle-Orléans Cajun Delights','Shelley Burke','Acheteur','P.O. Box 78934','Nouvelle-Orléans','LA','70117','Etats-Unis','(100) 555-4822',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('3','Grandma Kelly''s Homestead','Regina Murphy','Représentant(e)','707 Oxford Rd.','Ann Arbor','MI','48104','Etats-Unis','(313) 555-5735','(313) 555-3349');
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('4','Tokyo Traders','Yoshi Nagase','Directeur du marketing','9-8 Sekimai
Musashino-shi','Tokyo',null,'100','Japon','(03) 3555-5011',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('5','Cooperativa de Quesos ''Las Cabras''','Antonio del Valle Saavedra ','Responsable export','Calle del Rosal 4','Oviedo','Asturias','33007','Espagne','(98) 598 76 54',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('6','Mayumi''s','Mayumi Ohno','Chef de produit','92 Setsuko
Chuo-ku','Osaka',null,'545','Japon','(06) 431-7877',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('7','Pavlova, Ltd.','Ian Devling','Directeur du marketing','74 Rose St.
Moonie Ponds','Melbourne','Victoria','3058','Australie','(059) 55-5450','(03) 444-6588');
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('8','Specialty Biscuits, Ltd.','Peter Wilson','Représentant(e)','29 King''s Way','Manchester',null,'M14 GSD','Royaume-Uni','(161) 555-4448',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('9','PB Knäckebröd AB','Lars Peterson','Assistant(e) des ventes','Kaloadagatan 13','Göteborg',null,'S-345 67','Suède','031-987 65 43','031-987 65 91');
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('10','Refrescos Americanas LTDA','Carlos Diaz','Directeur du marketing','Av. das Americanas 12.890','São Paulo',null,'5442','Brésil','(11) 555 4640',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('11','Heli Süßwaren GmbH and Co. KG','Petra Winkler','Chef des ventes','Tiergartenstraße 5','Berlin',null,'10785','Allemagne','(010) 9984510',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('12','Plutzer Lebensmittelgroßmärkte AG','Martin Bein','Directeur du marketing international','Bogenallee 51','Frankfurt',null,'60439','Allemagne','(069) 992755',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('13','Nord-Ost-Fisch Handelsgesellschaft mbH','Sven Petersen','Responsable export','Frahmredder 112a','Cuxhaven',null,'27478','Allemagne','(04721) 8713','(04721) 8714');
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('14','Formaggi Fortini s.r.l.','Elio Rossi','Représentant(e)','Viale Dante, 75','Ravenna',null,'48100','Italie','(0544) 60323','(0544) 60603');
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('15','Norske Meierier','Beate Vileid','Directeur du marketing','Hatlevegen 5','Sandvika',null,'1320','Norvège','(0)2-953010',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('16','Bigfoot Breweries','Cheryl Saylor','Responsable de zone','3400 - 8th Avenue
Suite 210','Bend','OR','97101','Etats-Unis','(503) 555-9931',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('17','Svensk Sjöföda AB','Michael Björn','Représentant(e)','Brovallavägen 231','Stockholm',null,'S-123 45','Suède','08-123 45 67',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('18','Aux joyeux ecclésiastiques','Guylène Nodier','Chef des ventes','203, Rue des Francs-Bourgeois','Paris',null,'75004','France','01.03.83.00.68','01.03.83.00.62');
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('19','New England Seafood Cannery','Robb Merchant','Responsable de zone','Order Processing Dept.
2100 Paul Revere Blvd.','Boston','MA','02134','Etats-Unis','(617) 555-3267','(617) 555-3389');
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('20','Leka Trading','Chandra Leka','Propriétaire','471 Serangoon Loop, Suite #402','Singapore',null,'0512','Singapour','555-8787',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('21','Lyngbysild','Niels Petersen','Chef des ventes','Lyngbysild
Fiskebakken 10','Lyngby',null,'2800','Danemark','43844108','43844115');
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('22','Zaanse Snoepfabriek','Dirk Luchte','Chef comptable','Verkoop
Rijnweg 22','Zaandam',null,'9999 ZZ','Pays-Bas','(12345)1212','(12345) 1210');
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('23','Karkki Oy','Anne Heikkonen','Chef de produit','Valtakatu 12','Lappeenranta',null,'53120','Finlande','(953) 10956',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('24','G''day, Mate','Wendy Mackenzie','Représentant(e)','170 Prince Edward Parade
Hunter''s Hill','Sydney','NSW','2042','Australie',null,'(02) 555-4873');
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('25','Ma Maison','Jean-Guy Lauzon','Directeur du marketing','2960 Rue St. Laurent','Montréal','Québec','H1J 1C3','Canada','(514) 555-9022',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('26','Pasta Buttini s.r.l.','Giovanni Giudici','Acheteur','Via dei Gelsomini, 153','Salerno',null,'84100','Italie','(089) 6547665','(089) 6547667');
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('27','Escargots Nouveaux','Marie Delamare','Chef des ventes','22, rue H. Voiron','Montceau',null,'71300','France','04.85.57.00.07',null);
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('28','Gai pâturage','Eliane Noz','Représentant(e)','Bat. B
3, rue des Alpes','Annecy',null,'74000','France','04.38.76.98.06','04.38.76.98.58');
Insert into FOURNISSEURS (NFOURNISSEUR,SOCIÉTÉFOUR,CONTACTFOUR,FONCTIONFOUR,ADRESSEFOUR,VILLEFOUR,RÉGIONFOUR,CODEPOSTAL,PAYSFOUR,TÉLFOUR,FAXFOUR) values ('29','Forêts d''érables','Chantal Goulet','Chef comptable','148 rue Chasseur','Ste-Hyacinthe','Québec','J2S 7S8','Canada','(514) 555-2955','(514) 555-2921');
